### ISSUE TITLE
Add region in google_compute_network / subnetwork

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-lb-internal#18]
On the [subnetwork datasource](https://github.com/terraform-google-modules/terraform-google-lb-internal/blob/master/main.tf#L24), we should add the `region` parameter: indeed, if it is unset in the provider, the module will fail to run:

![Screenshot 2019-11-13 at 18 39 20](https://user-images.githubusercontent.com/9629314/68789060-f4091480-0644-11ea-8db8-9663d6544096.png)

However, setting it in the provider is not always the right thing to do (if you work with multiple regions for instance), and it would be nice to be able to pass it explicitely to the datasource.

Can we please add a `region` variable ?

**Comment by morgante** [comment]
There's already a region variable, so it would be a simple matter of adding it to the data source.

PR welcome.

**Comment by omazin** [comment]
The `region` variable is already added in the #16
