### ISSUE TITLE
Issue for me 

### ISSUE THREAD

**Issue by Praveen537** [terraform-google-modules/terraform-google-lb-internal#32]
i have cloned the code and ran it , I am getting below error ..  suggest me what could be the issue

 
Error: Error creating HealthCheck: googleapi: Error 409: The resource 'projects/praveen-sahukara/global/healthChecks/group-ilb-hc-http' already exists, alreadyExists

  on .terraform/modules/gce-ilb/terraform-google-lb-internal-2.1.0/main.tf line 80, in resource "google_compute_health_check" "http":
  80: resource "google_compute_health_check" "http" {

Error: Error creating HttpHealthCheck: googleapi: Error 409: The resource 'projects/praveen-sahukara/global/httpHealthChecks/group1-lb-hc' already exists, alreadyExists

  on .terraform/modules/gce-lb-fr/terraform-google-lb-2.2.0/main.tf line 41, in resource "google_compute_http_health_check" "default":
  41: resource "google_compute_http_health_check" "default" {

Error: cannot determine self_link for subnetwork "mysubnet-01": Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.

  on .terraform/modules/instance_template2/terraform-google-vm-1.4.1/modules/instance_template/main.tf line 57, in resource "google_compute_instance_template" "tpl":
  57: resource "google_compute_instance_template" "tpl" {

Error: cannot determine self_link for subnetwork "mysubnet-01": Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.

  on .terraform/modules/instance_template3/terraform-google-vm-1.4.1/modules/instance_template/main.tf line 57, in resource "google_compute_instance_template" "tpl":
  57: resource "google_compute_instance_template" "tpl" {

**Comment by morgante** [comment]
It sounds like you're attempting to create a resource which already exists. Please choose a different name.
