### ISSUE TITLE
issue iwth health_check and port_name var

### ISSUE THREAD

**Issue by git4rockyt** [terraform-google-modules/terraform-google-lb-internal#33]
When using this module with health_check, we have to pass in the port_name variable in the health_check object but that clashes with the code in main.tf on line 75 and 95.

The issue is resolved if we set "provider = google-beta" for the resources resource "google_compute_health_check" "tcp" & resource "google_compute_health_check" "http"
       

Error: Unsupported argument
  on .terraform/modules/gce-ilb/terraform-google-lb-internal-2.1.0/main.tf line 75, in resource "google_compute_health_check" "tcp":
  75:     port_name    = var.health_check["port_name"]
An argument named "port_name" is not expected here.
Error: Unsupported argument
  on .terraform/modules/gce-ilb/terraform-google-lb-internal-2.1.0/main.tf line 95, in resource "google_compute_health_check" "http":
  95:     port_name    = var.health_check["port_name"]
An argument named "port_name" is not expected here.

**Comment by morgante** [comment]
What version of the Google provider are you using?

**Comment by git4rockyt** [comment]
provider "google" {
  version = "~> 2.10.0"
}

**Comment by morgante** [comment]
Please try upgrading to a newer provider version (ex. 3.20), as I believe that should fix the version.
