### ISSUE TITLE
l7 (http) internal lb ?

### ISSUE THREAD

**Issue by naseemkullah** [terraform-google-modules/terraform-google-lb-internal#38]
Hello, we are looking to manage a https://cloud.google.com/load-balancing/docs/l7-internal via terraform. I take it this nor https://github.com/terraform-google-modules/terraform-google-lb-httpe are a good fit? Would this be its own module or a submodule in one of these?

**Comment by morgante** [comment]
It could be a submodule of this.

**Comment by tpoindessous** [comment]
Hi @morgante 

There is a PR for this : https://github.com/terraform-google-modules/terraform-google-lb-internal/pull/37

Maybe you could, please, tell the authors to rebase his PR against lb-http module ;) 

Thanks for your work !
