### ISSUE TITLE
Make a variable for backend timeout

### ISSUE THREAD

**Issue by denissimonovski** [terraform-google-modules/terraform-google-lb-internal#53]
Can we refactor this hardcoded value with a variable?
https://github.com/terraform-google-modules/terraform-google-lb-internal/blob/12eb7702ca744743a45a2624c2fffe25b2c53908/main.tf#L51

**Comment by morgante** [comment]
Should we potentially just use the same timeout as the health_check?

**Comment by denissimonovski** [comment]
I think that would be way better than this. It would be a great start, at least.

**Comment by morgante** [comment]
Sounds good, I've put it into our backlog. If you want to open a pull request, we'd be happy to review and it will likely land sooner.

**Comment by denissimonovski** [comment]
That's great. I'll take a look into this next week.

**Comment by denissimonovski** [comment]
@morgante I found this in the GCP docs:

> For internal TCP/UDP load balancers and network load balancers, you can set the value of the backend service timeout using gcloud or the API, but the value is ignored. Backend service timeout has no meaning for these pass-through load balancers.
Source: https://cloud.google.com/load-balancing/docs/backend-service#timeout-setting 

So whatever we put in the line I opened my issue for, doesn't make any difference. Since this is already an optional variable is it better to remove that line altogether and keep it clean? I can do it if you approve.

**Comment by morgante** [comment]
@denissimonovski Yes, go ahead and remove it. Please also leave a comment linking to this issue so we remember not to add it back.

**Comment by denissimonovski** [comment]
@morgante where should I put the comment?

**Comment by denissimonovski** [comment]
@morgante how about now?

**Comment by denissimonovski** [comment]
@morgante now?
