### ISSUE TITLE
[Ask] load_balancing_scheme INTERNAL is hardcoded

### ISSUE THREAD

**Issue by prima101112** [terraform-google-modules/terraform-google-lb-internal#60]
**[Ask] load_balancing_scheme INTERNAL is hardcoded**

is there any module to create internal_managed lb? we face issue 
1 MIG with 2 different LB 

- 1 LB is http external
- 1 LB is internal 

its all failed due to different balancing mode
http external is using **utilization** and internal lb just accept **connection** 
could we somehow make load_balancing_scheme in the var

**Comment by morgante** [comment]
I do not follow your question.

This module is for creating an INTERNAL load balancer. If you want to create an external HTTP load balancer, use [this module](https://github.com/terraform-google-modules/terraform-google-lb-http).
